# Travis file inspired by https://github.com/ellerbrock/travis-link-checker
# 

sudo: false

language: bash

services:
  - docker
  
# URL_TO_CHECK is the url checked for broken links,
# RECURSION_LEVEL is the -r option of linkcheck, 
# described as : "Check recursively all links up to given depth. A
# negative depth will enable infinite recursion. Default
# depth is infinite."
# for wiki.codyco.eu we need a finite RECURSION_LEVEL, otherwise 
# we finish the time available for a travis build 
env:
  - URL_TO_CHECK=http://yarp.it 

install:
  - docker pull ellerbrock/link-checker

script:
  - docker run ellerbrock/link-checker --check-extern ${URL_TO_CHECK}

notifications:
  email:
    on_success: never
    on_failure: always
